#!/bin/bash

#set -x

clear

echo "<-- Olarila.com - The Real Vanilla Hackintosh -->"

xcode-select --install
sudo xcode-select --switch /Library/Developer/CommandLineTools
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

echo "            "
echo "##### !!! DOWNLOADING FILES !!! #####"
echo "            "
mkdir /$HOME/Desktop/Lilu4All
cd /$HOME/Desktop/Lilu4All
git clone https://github.com/acidanthera/MacKernelSDK
git clone https://github.com/acidanthera/Lilu
git clone https://github.com/acidanthera/RestrictEvents
git clone https://github.com/acidanthera/AppleALC
git clone https://github.com/acidanthera/AirportBrcmFixup
git clone https://github.com/acidanthera/EmeraldSDHC
git clone https://github.com/acidanthera/WhateverGreen
git clone https://github.com/acidanthera/NVMeFix
git clone https://github.com/acidanthera/BrightnessKeys
git clone https://github.com/acidanthera/HibernationFixup
git clone https://github.com/acidanthera/DebugEnhancer
git clone https://github.com/acidanthera/CpuTscSync
git clone https://github.com/acidanthera/CryptexFixup
git clone https://github.com/acidanthera/FeatureUnlock
git clone https://github.com/acidanthera/CPUFriend
git clone https://github.com/acidanthera/VoodooPS2
git clone https://github.com/acidanthera/IntelMausi
git clone https://github.com/acidanthera/RTCMemoryFixup
git clone https://github.com/acidanthera/VirtualSMC

echo "            "
echo "##### !!! COPY LILU TO FOLDERS !!! #####"
echo "            "
cd /$HOME/Desktop/Lilu4All
cp -r ./MacKernelSDK ./Lilu
xcodebuild -project ./Lilu/Lilu.xcodeproj -configuration Debug clean build ARCHS=x86_64 ONLY_ACTIVE_ARCH=YES CONFIGURATION_BUILD_DIR=/$HOME/Desktop/Lilu4All/Release
cd /$HOME/Desktop/Lilu4All
cp -r ./Release/Lilu.kext ./RestrictEvents
cp -r ./Release/Lilu.kext ./AppleALC
cp -r ./Release/Lilu.kext ./AirportBrcmFixup
cp -r ./Release/Lilu.kext ./EmeraldSDHC
cp -r ./Release/Lilu.kext ./WhateverGreen
cp -r ./Release/Lilu.kext ./NVMeFix
cp -r ./Release/Lilu.kext ./BrightnessKeys
cp -r ./Release/Lilu.kext ./HibernationFixup
cp -r ./Release/Lilu.kext ./DebugEnhancer
cp -r ./Release/Lilu.kext ./CpuTscSync
cp -r ./Release/Lilu.kext ./CryptexFixup
cp -r ./Release/Lilu.kext ./FeatureUnlock
cp -r ./Release/Lilu.kext ./CPUFriend
cp -r ./Release/Lilu.kext ./VoodooPS2
cp -r ./Release/Lilu.kext ./IntelMausi
cp -r ./Release/Lilu.kext ./RTCMemoryFixup
cp -r ./Release/Lilu.kext ./VirtualSMC

echo "            "
echo "##### !!! COPY MacKernelSDK TO FOLDERS !!! #####"
echo "            "
cd /$HOME/Desktop/Lilu4All
cp -r ./MacKernelSDK ./RestrictEvents
cp -r ./MacKernelSDK ./AppleALC
cp -r ./MacKernelSDK ./AirportBrcmFixup
cp -r ./MacKernelSDK ./EmeraldSDHC
cp -r ./MacKernelSDK ./WhateverGreen
cp -r ./MacKernelSDK ./NVMeFix
cp -r ./MacKernelSDK ./BrightnessKeys
cp -r ./MacKernelSDK ./HibernationFixup
cp -r ./MacKernelSDK ./DebugEnhancer
cp -r ./MacKernelSDK ./CpuTscSync
cp -r ./MacKernelSDK ./CryptexFixup
cp -r ./MacKernelSDK ./FeatureUnlock
cp -r ./MacKernelSDK ./CPUFriend
cp -r ./MacKernelSDK ./VoodooPS2
cp -r ./MacKernelSDK ./IntelMausi
cp -r ./MacKernelSDK ./RTCMemoryFixup
cp -r ./MacKernelSDK ./VirtualSMC

echo "            "
echo "##### !!! START BUILD FILES !!! #####"
echo "            "
cd /$HOME/Desktop/Lilu4All/RestrictEvents/
xcodebuild CONFIGURATION_BUILD_DIR=/$HOME/Desktop/Lilu4All/Release
cd /$HOME/Desktop/Lilu4All/AppleALC/
xcodebuild CONFIGURATION_BUILD_DIR=/$HOME/Desktop/Lilu4All/Release
cd /$HOME/Desktop/Lilu4All/AirportBrcmFixup/
xcodebuild CONFIGURATION_BUILD_DIR=/$HOME/Desktop/Lilu4All/Release
cd /$HOME/Desktop/Lilu4All/EmeraldSDHC/
xcodebuild CONFIGURATION_BUILD_DIR=/$HOME/Desktop/Lilu4All/Release
cd /$HOME/Desktop/Lilu4All/WhateverGreen/
xcodebuild CONFIGURATION_BUILD_DIR=/$HOME/Desktop/Lilu4All/Release
cd /$HOME/Desktop/Lilu4All/NVMeFix/
xcodebuild CONFIGURATION_BUILD_DIR=/$HOME/Desktop/Lilu4All/Release
cd /$HOME/Desktop/Lilu4All/BrightnessKeys/
xcodebuild CONFIGURATION_BUILD_DIR=/$HOME/Desktop/Lilu4All/Release
cd /$HOME/Desktop/Lilu4All/HibernationFixup/
xcodebuild CONFIGURATION_BUILD_DIR=/$HOME/Desktop/Lilu4All/Release
cd /$HOME/Desktop/Lilu4All/DebugEnhancer/
xcodebuild CONFIGURATION_BUILD_DIR=/$HOME/Desktop/Lilu4All/Release
cd /$HOME/Desktop/Lilu4All/CpuTscSync/
xcodebuild CONFIGURATION_BUILD_DIR=/$HOME/Desktop/Lilu4All/Release
cd /$HOME/Desktop/Lilu4All/CryptexFixup/
xcodebuild CONFIGURATION_BUILD_DIR=/$HOME/Desktop/Lilu4All/Release
cd /$HOME/Desktop/Lilu4All/FeatureUnlock/
xcodebuild CONFIGURATION_BUILD_DIR=/$HOME/Desktop/Lilu4All/Release
cd /$HOME/Desktop/Lilu4All/CPUFriend/
xcodebuild CONFIGURATION_BUILD_DIR=/$HOME/Desktop/Lilu4All/Release
cd /$HOME/Desktop/Lilu4All/VoodooPS2/
xcodebuild CONFIGURATION_BUILD_DIR=/$HOME/Desktop/Lilu4All/Release
cd /$HOME/Desktop/Lilu4All/IntelMausi/
xcodebuild CONFIGURATION_BUILD_DIR=/$HOME/Desktop/Lilu4All/Release
cd /$HOME/Desktop/Lilu4All/RTCMemoryFixup/
xcodebuild CONFIGURATION_BUILD_DIR=/$HOME/Desktop/Lilu4All/Release
cd /$HOME/Desktop/Lilu4All/VirtualSMC/
xcodebuild CONFIGURATION_BUILD_DIR=/$HOME/Desktop/Lilu4All/Release
cd /$HOME/Desktop/Lilu4All/Lilu/
xcodebuild CONFIGURATION_BUILD_DIR=/$HOME/Desktop/Lilu4All/Release

mv ~/Desktop/Lilu4All/Release/package/Kexts ~/Desktop/